import os
import re
Import('env')
env = env.Clone()

env.Append(LIBS = ['m','pthread', 'decoder', 'spectgen', 'tag_c'])
env.Append(CPPPATH = ['/usr/include/taglib'])

install_libs = []
prefix = '/usr'
lib_path = prefix + "/lib"

HISTDB_SOURCES = [
	"find.c",
	"genhistdb.c",
	"hist.c",
	"hist_dist.c",
	"list.c"
]

install_libs += env.SharedLibrary('histdb', HISTDB_SOURCES)

inst = env.Install(lib_path, install_libs)
env.Alias( "install", inst )
env.Depends( inst, install_libs )
Ignore( '.', inst )

