import os
import re
env = Environment()

env.Append(LIBS = ['m','pthread', 'fftw3f', 'decoder'])
env.Append(CPPPATH = ['../../include'])
env.Append(LIBPATH = ['../decoder'])

# Let the programs know how much memory you have
for line in open('/proc/meminfo', 'r').read().split('\n'):
	if(not line.strip().find("MemTotal: ")):
		numbers = re.search("([0-9]+)", line.strip()).group(0)
		env.Append(CCFLAGS = '-DMEMORY_SIZE=' + numbers)


install_libs = []
prefix = '/usr'
lib_path = prefix + "/lib"

SPECTGEN_SOURCES = [
	"spectgen.c"
]

install_libs += env.SharedLibrary('spectgen', SPECTGEN_SOURCES)

env.Alias('install', env.Install(lib_path, install_libs))

if 'uninstall' in COMMAND_LINE_TARGETS:
	env.Command("uninstall", None, Delete(FindInstalledFiles()))


