#*******************************************************************************
#    This file is part of spectro
#    Copyright (C) 2011  Amithash Prasad <amithash@gmail.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#*******************************************************************************

import os
import re
Import('env')
env = env.Clone()

env.Append(LIBS = ['m','pthread', 'fftw3f', 'decoder'])

install_libs = []
prefix = '/usr'
lib_path = prefix + "/lib"

SPECTGEN_SOURCES = [
	"spectgen.c",
	"spectgen_session.c",
	"scale.c"
]

install_libs += env.SharedLibrary('spectgen', SPECTGEN_SOURCES)

inst = env.Install(lib_path, install_libs)
env.Alias( "install", inst )
env.Depends( inst, install_libs )
Ignore( '.', inst )

