import os
import re
Import('env')
env = env.Clone()

env.Append(LIBS = ['m','pthread', 'fftw3f', 'decoder'])

install_libs = []
prefix = '/usr'
lib_path = prefix + "/lib"

SPECTGEN_SOURCES = [
	"spectgen.c",
	"spectgen_session.c"
]

install_libs += env.SharedLibrary('spectgen', SPECTGEN_SOURCES)

inst = env.Install(lib_path, install_libs)
env.Alias( "install", inst )
env.Depends( inst, install_libs )
Ignore( '.', inst )

