import os
env = Environment()
Export('env')

subdirs = [
	"decoder",
	"spectgen",
	"histdb"
]

if 'uninstall' in COMMAND_LINE_TARGETS:
	for dir in installdirs:
		os.system("scons -C " + dir + " uninstall")
else:
	SConscript(dirs=subdirs, name = "SConstruct")
