import os
env = Environment()

env.Append(LIBS = ['m','pthread', 'fftw3f', 'spect', 'tag_c'])
env.Append(LIBPATH = ['../lib'])
env.Append(CPPPATH = ['../lib','/usr/include/taglib'])
env.Append(CCFLAGS = ['-O3'])

install_programs = []
install_libs = []
prefix = '/usr'
bin_path = prefix + "/bin"
lib_path = prefix + "/lib"


SPECT2CSV_SOURCES = [
	"spect2csv.c"
]
install_programs += env.Program('spect2csv', SPECT2CSV_SOURCES)

SPECT2HIST_SOURCES = [
	"spect2hist.c"
]
install_programs += env.Program('spect2hist', SPECT2HIST_SOURCES)

GENSPECTDB_SOURCES = [
	"genspectdb.c"
]
install_programs += env.Program('genspectdb', GENSPECTDB_SOURCES)

HIST2PGM_SOURCES = [
	"hist2pgm.c"
]
install_programs += env.Program('hist2pgm', HIST2PGM_SOURCES)

GETSIMILAR_SOURCES = [
	"getsimilar.c"
]
install_programs += env.Program('getsimilar', GETSIMILAR_SOURCES)

PLOTBPM_SOURCES = [
	"plotbpm.c",
	"dwt.c"
]
install_programs += env.Program('plotbpm', PLOTBPM_SOURCES)

PLOTHIST_SOURCES = [
	"plothist.c"
]
install_programs += env.Program('plothist', PLOTHIST_SOURCES)

NORM_SPECTDB_SOURCES = [
	"norm_spect.c"
]
install_programs += env.Program('normspectdb', NORM_SPECTDB_SOURCES)

IEL_SOURCES = [
	"inv_equal_loudness_vals.c"
]
install_programs += env.Program('inv_equal_loudness_vals', IEL_SOURCES)

env.Alias('install', env.Install(bin_path, install_programs))
env.Alias('install', env.Install(lib_path, install_libs))

if 'uninstall' in COMMAND_LINE_TARGETS:
	env.Command("uninstall", None, Delete(FindInstalledFiles()))



