Import('env')
env = env.Clone()

env.Append(LIBS = ['m','pthread', 'decoder', 'spectgen', 'histdb'])

install_programs = []
install_libs = []
prefix = '/usr'
bin_path = prefix + "/bin"

SPECTGEN_APP_SOURCES = [
	"spectgen_app.c"
]
install_programs += env.Program('spectgen', SPECTGEN_APP_SOURCES)

DECODER_APP_SOURCES = [
	"decoder_app.c"
]
install_programs += env.Program('decoder', DECODER_APP_SOURCES)

GENHISTDB_APP_SOURCES = [
	"genhistdb_app.c"
]
install_programs += env.Program('genhistdb', GENHISTDB_APP_SOURCES)

GETSIMILAR_SOURCES = [
	"getsimilar.c"
]
install_programs += env.Program('getsimilar', GETSIMILAR_SOURCES)

inst = env.Install(bin_path, install_programs)
env.Alias( "install", inst )
env.Depends( inst, install_programs )
Ignore( '.', inst )

