#*******************************************************************************
#    This file is part of spectro
#    Copyright (C) 2011  Amithash Prasad <amithash@gmail.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#*******************************************************************************
Import('env')
env = env.Clone()

env.Append(LIBS = ['m','pthread', 'decoder', 'spectgen', 'histdb'])

install_programs = []
install_libs = []
prefix = '/usr'
bin_path = prefix + "/bin"

SPECTGEN_APP_SOURCES = [
	"spectgen_app.c"
]
install_programs += env.Program('spectgen', SPECTGEN_APP_SOURCES)

DECODER_APP_SOURCES = [
	"decoder_app.c"
]
install_programs += env.Program('decoder', DECODER_APP_SOURCES)

GENHISTDB_APP_SOURCES = [
	"genhistdb_app.c"
]
install_programs += env.Program('genhistdb', GENHISTDB_APP_SOURCES)

GETSIMILAR_SOURCES = [
	"getsimilar.c"
]
install_programs += env.Program('getsimilar', GETSIMILAR_SOURCES)

inst = env.Install(bin_path, install_programs)
env.Alias( "install", inst )
env.Depends( inst, install_programs )
Ignore( '.', inst )

