bld_moc = Builder(action = '/usr/bin/moc-qt4 ${MOCFLAGS} -I. ${SOURCE} -o ${TARGET}')
env = Environment(BUILDERS = {'GenMoc' : bld_moc})


install_programs = []
install_libs = []
prefix = '/usr'
bin_path = prefix + "/bin"
lib_path = prefix + "/lib"


DEFINES = [
"-D_REENTRANT",
"-DQT_NO_DEBUG",
"-DQT_PHONON_LIB",
"-DQT_GUI_LIB",
"-DQT_CORE_LIB",
"-DQT_SHARED"
]

env.Append(MOCFLAGS = [
	DEFINES			
])

env.Append(CCFLAGS = [
	"-pipe",
	"-O2",
	"-Wall",
	"-W",
] + DEFINES )

env.Append(CPPPATH = [
	"/usr/include/qt4/QtCore",
	"/usr/include/qt4/QtGui",
	"/usr/include/phonon",
	"/usr/include/qt4",
	"/usr/include/qt4/phonon_compat",
	".",
	"../include"
])

env.Append(LIBPATH = [
	"/usr/lib",
	"."
])

env.Append(LIBS = [
	"m",
	"phonon",
	"QtGui",
	"QtCore",
	"pthread"
])

moc_out = env.GenMoc('moc_mainwindow.cpp', 'mainwindow.h')

SOURCES = [
	'mainwindow.cpp',
	'main.cpp',
	'hist.cpp',
]
install_programs += env.Program('spectradio', [SOURCES + moc_out])

env.Alias('install', env.Install(bin_path, install_programs))
env.Alias('install', env.Install(lib_path, install_libs))

if 'uninstall' in COMMAND_LINE_TARGETS:
	env.Command("uninstall", None, Delete(FindInstalledFiles()))

