import os
import re
Import('env')

env = env.Clone()

env.Append(LIBS = ['m','pthread', 'mpg123', 'vorbisfile'])

install_libs = []
prefix = '/usr'
lib_path = prefix + "/lib"

DECODER_SOURCES = [
	"decoder.c",
	"decoder_backend.c",
	"decoder_backend_mpg123.c",
	"decoder_backend_vorbis.c",
	"queue.c"
]

install_libs += env.SharedLibrary('decoder', DECODER_SOURCES)

inst = env.Install(lib_path, install_libs)
env.Alias( "install", inst )
env.Depends( inst, install_libs )
Ignore( '.', inst )

